language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm run build
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $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 # Set in the settings page of your repository, as a secure variable
    keep_history: true
    on:
        branch: master
